import { objectMap, times } from "../utils";

describe("times", () => {
  it("generates array of n with value generated by callback", () => {
    const arr = times((index) => index * 10, 3);

    expect(arr).toEqual([0, 10, 20]);
  });
});

describe("objMap", () => {
  it("iterates through object and changes its values", () => {
    const base = { a: 4, b: 3 };
    const doubled = objectMap(base, (value) => value * 2);

    expect(doubled).toEqual({ a: 8, b: 6 });
  });
});
